version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build_image:
    working_directory: ~/circle/git/fb-av
    docker: &ecr_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys: &ssh_keys
          fingerprints:
            - db:58:12:22:b9:f9:7d:b3:97:71:c2:a4:a8:1e:a1:95
      - run: &base_environment_variables
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_db581222b9f97db39771c2a4a81ea195" >> $BASH_ENV
      - run: &deploy_scripts
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
  deploy_to_test:
    working_directory: ~/circle/git/fb-av
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to test dev in EKS
          environment:
            APPLICATION_NAME: fb-av
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-platform-test-dev
          command: './deploy-scripts/bin/deploy-eks'
      - run:
          name: deploy to test production in EKS
          environment:
            APPLICATION_NAME: fb-av
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-platform-test-production
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: master
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  deploy_to_saas_test:
    working_directory: ~/circle/git/fb-av
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to saas test in EKS
          environment:
            APPLICATION_NAME: fb-av
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-saas-test
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: *slack_status
  # acceptance_tests:
  #   docker: *ecr_image
  #   resource_class: large
  #   steps:
  #     - setup_remote_docker
  #     - run: *deploy_scripts
  #     - run:
  #         name: Run acceptance tests
  #         command: './deploy-scripts/bin/acceptance_tests'
  #     - slack/status: *slack_status
  deploy_to_live:
    working_directory: ~/circle/git/fb-av
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to live dev in EKS
          environment:
            APPLICATION_NAME: fb-av
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-platform-live-dev
          command: './deploy-scripts/bin/deploy-eks'
      - run:
          name: deploy to live production in EKS
          environment:
            APPLICATION_NAME: fb-av
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-platform-live-production
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status:
          only_for_branches: master
          success_message: ":rocket:  Successfully deployed to Live  :guitar:"
          failure_message: ":alert:  Failed to deploy to Live  :try_not_to_cry:"
          include_job_number_field: false
  deploy_to_saas_live:
    working_directory: ~/circle/git/fb-av
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to saas live in EKS
          environment:
            APPLICATION_NAME: fb-av
            PLATFORM_ENV: live
            K8S_NAMESPACE: formbuilder-saas-live
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: *slack_status
  smoke_tests:
    docker: *ecr_image
    steps:
      - setup_remote_docker
      - run: *deploy_scripts
      - run:
          name: Run smoke tests
          command: './deploy-scripts/bin/smoke_tests'
      - slack/status: *slack_status

workflows:
  version: 2
  build:
    jobs:
      - build_image:
          context: &context
            - moj-forms
            - moj-forms-platform-apps
          filters:
            branches:
              only:
                - master
                - update-circleci
      - deploy_to_test:
          context: *context
          requires:
            - build_image
      - deploy_to_saas_test:
          context: *context
          requires:
            - build_image
      # - acceptance_tests:
      #     requires:
      #       - deploy_to_test
      #       - deploy_to_saas_test
      #     filters:
      #       branches:
      #         only:
      #           - master
      - slack/approval-notification:
          message: ":portalorangeparrot:  Deployment to Live pending approval  :portalblueparrot:"
          include_job_number_field: false
          requires:
            # - acceptance_tests
            - deploy_to_test
            - deploy_to_saas_test
      - confirm_live_deploy:
          type: approval
          requires:
            # - acceptance_tests
            - deploy_to_test
            - deploy_to_saas_test
      - deploy_to_live:
          context: *context
          requires:
            - confirm_live_deploy
      - deploy_to_saas_live:
          context: *context
          requires:
            - confirm_live_deploy
      - smoke_tests:
          requires:
            - deploy_to_live
