---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fb-av-{{ .Values.environmentName }}"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: "fb-av-{{ .Values.environmentName }}"
  template:
    metadata:
      labels:
        app: "fb-av-{{ .Values.environmentName }}"
        appGroup: "fb-av"
        fb-service-token-cache-access: "false"
        tier: "frontend"
    spec:
      serviceAccountName: "formbuilder-av-{{ .Values.environmentName }}"
      terminationGracePeriodSeconds: 120
      containers:
      - name: "fb-av-{{ .Values.environmentName }}"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-av:{{ .Values.circleSha1 }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 25m
            memory: 1024Mi
          limits:
            cpu: 150m
            memory: 3500Mi
        ports:
          - name: clamav-port
            containerPort: 3310
        startupProbe:
          tcpSocket:
            port: clamav-port
          failureThreshold: 30
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: clamav-port
          periodSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "killall -SIGTERM clamd; while [ -S /tmp/clamd.sock ]; do sleep 1; done"]
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: fb-av-env-{{ .Values.environmentName }}
        env:
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-av-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
